[package]
name = "rustclamp-example-site-server"
version = "0.1.0"
edition = "2024"
rust-version = "1.96.1"
publish = false

[workspace]
resolver = "3"

[dependencies]
rustclamp-core = { version = "0.1.0", path = "../../../core" }
rustclamp-http = { version = "0.1.0", path = "../../../http" }
rustclamp-kernel = { version = "0.1.0", path = "../../../kernel" }
tokio = { version = "1.53.1", features = ["macros", "net", "rt-multi-thread"] }

[[example]]
name = "13-site-server"
path = "main.rs"

[lints.rust]
unsafe_code = "forbid"
missing_docs = "deny"

[lints.rustdoc]
broken_intra_doc_links = "deny"
