[package]
name = "rustclamp-example-process"
version = "0.1.0"
edition = "2024"
rust-version = "1.96.1"
publish = false

[dependencies]
rustclamp-core = { version = "0.1.0", path = "../../../core" }
rustclamp-kernel = { version = "0.1.0", path = "../../../kernel" }
rustclamp-tooling = { version = "0.1.0", path = "../../tooling", optional = true }

[features]
tooling-inspection = ["dep:rustclamp-tooling"]

[[example]]
name = "inspection-json"
path = "examples/inspection-json.rs"
required-features = ["tooling-inspection"]

[workspace]

[profile.release]
opt-level = 3
debug = false
strip = "none"
lto = false
codegen-units = 16
panic = "unwind"
