#!/usr/bin/env python3
"""Generate local Cargo coordination without changing package manifests."""

import argparse
from pathlib import Path
import shutil
import subprocess
import tempfile

REPOS = ("rustclamp", "core", "kernel", "runtime")
MANIFEST = '''# Generated by rustclamp/tools/workspace.py; local coordination only.
[workspace]
resolver = "3"
members = ["rustclamp", "core", "kernel", "runtime"]
exclude = ["experiments", "playground"]

[profile.release]
opt-level = 3
debug = false
strip = "none"
lto = false
codegen-units = 16
panic = "unwind"
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    args = parser.parse_args()
    root = args.root.resolve()
    for repo in REPOS:
        if not (root / repo / "Cargo.toml").is_file():
            parser.error(f"missing sibling package: {root / repo}")
    outputs = {
        root / "Cargo.toml": MANIFEST,
        root / "rust-toolchain.toml": (root / "rustclamp/rust-toolchain.toml").read_text(),
    }
    for path, content in outputs.items():
        if path.exists() and path.read_text() != content:
            parser.error(f"refusing to replace differing file: {path}")
    for path, content in outputs.items():
        path.write_text(content)
    (root / "workspace").mkdir(exist_ok=True)
    for repo in REPOS:
        lock = root / repo / "Cargo.lock"
        if not lock.exists():
            # Standalone lockfiles remain owned by their individual repositories.
            with tempfile.TemporaryDirectory(prefix="clamp-lock-") as tmp:
                dest = Path(tmp) / repo
                shutil.copytree(root / repo, dest, ignore=shutil.ignore_patterns(".git", "target"))
                subprocess.run(["cargo", "generate-lockfile", "--offline"], cwd=dest, check=True)
                shutil.copyfile(dest / "Cargo.lock", lock)
    print(f"Coordination manifest: {root / 'Cargo.toml'}")


if __name__ == "__main__":
    main()
